MODULO_1 = {
    "numero": 1,
    "nome": "Contexto Antes do Conteudo",
    "proposito": """Criar o problema que o conceito resolve. Quem nao tem background previo nao possui esquemas mentais para ancorar informacao nova. Sem ancoragem, o conceito chega como dado flutuante.""",
    "instrucao_central": """Antes de qualquer definicao, mecanismo ou terminologia tecnica, apresente uma situacao concreta com um DESFECHO INESPERADO E DRAMATICO. O desfecho nao e apenas 'algo estranho aconteceu'. E uma consequencia real na vida da personagem: algo foi descoberto, algo mudou, algo foi perdido, algo nao faz sentido. O estudante deve terminar de ler com desconforto ativo — com vontade real de entender o que aconteceu. Antes de escrever, o GPT deve se perguntar: 'Se eu fosse o estudante lendo isso, ficaria com vontade de saber o que aconteceu?' Se a resposta for nao, o desfecho esta fraco e deve ser reescrito.""",
    "regra_principal": """Nenhuma definicao antes da situacao. A situacao deve ser narrativa com personagem, verbos e sequencia temporal. A pergunta ao final deve ser genuina. Evite termos tecnicos na situacao.""",
    "criterios_obrigatorios": [
        "Nenhuma definicao antes da situacao. Nao comece com 'X e definido como...'.",
        "A situacao deve ser narrativa: use nomes, verbos e sequencia temporal. Sem bullets.",
        "DESFECHO OBRIGATORIO E DRAMATICO: algo aconteceu de verdade com a personagem. Uma consequencia real: um diagnostico inesperado, um sintoma que nao fazia sentido, uma decisao medica que surpreendeu, algo que mudou a vida da personagem de forma concreta. Narrar uma consulta ou um resultado de exame sem consequencia NAO e desfecho.",
        "TESTE INTERNO ANTES DE ESCREVER: pergunte-se 'Se eu fosse o estudante lendo isso, ficaria com vontade de saber o que aconteceu?' Se a resposta for nao, reescreva o desfecho.",
        "O desfecho nao pode entregar o mecanismo implicitamente. O estudante sente o misterio — nao deduz a causa.",
        "A pergunta geradora deve emergir do desfecho, nao da situacao inicial.",
        "A pergunta ao final deve ser genuina. O estudante nao pode saber a resposta ainda.",
        "Evite termos tecnicos em toda a etapa. O jargao entra no Modulo 2.",
    ],
    "estrutura_resposta": [
        "1. SITUACAO NARRATIVA: um ou dois paragrafos curtos. Linguagem acessivel. Personagem concreto, sequencia de eventos observaveis. Sem termos tecnicos.",
        "2. DESFECHO INESPERADO (obrigatorio): algo aconteceu com a personagem que nao faz sentido sem o mecanismo. Deve ser concreto, observavel e incompreensivel por senso comum. Sem vocabulario tecnico. Sem antecipar a explicacao. Este e o cliffhanger cognitivo — o estudante precisa querer saber o que aconteceu.",
        "3. PERGUNTA GERADORA: uma unica pergunta simples que emerge do desfecho. Deve ser algo que o estudante perceba que nao consegue responder ainda.",
        "4. FRASE DE TRANSICAO: 'E exatamente isso que o conceito de [X] responde. Vamos construir o mecanismo do zero.'",
        "5. NAO resolva a pergunta. A resolucao acontece no Modulo 2.",
    ],
    "o_que_nao_e": [
        "Nao e motivacao ('esse conteudo e importante porque...')",
        "Nao e contexto historico ('a penicilina foi descoberta em 1928...')",
        "Nao e overview do conteudo ('vamos ver X, Y e Z')",
        "Nao e definicao disfarcada de narrativa.",
        "Nao e narrar uma consulta ou coleta de exame sem consequencia. 'Paciente foi ao laboratorio e o resultado tinha numeros alterados' NAO e desfecho — e apenas cenario.",
        "Nao e situacao + pergunta direta sem desfecho. Sem desfecho dramatico, o estudante nao tem tensao narrativa real.",
        "Nao e desfecho que entrega o mecanismo implicitamente.",
        "Nao e lista de numeros ou dados tecnicos como situacao. Dados so aparecem embutidos em narrativa, como parte do que a personagem viveu e sentiu.",
        "Nao e desfecho vago ('algo estranho aconteceu', 'os numeros estavam alterados'). O desfecho precisa de consequencia concreta e especifica.",
    ],
    "frases_modelo": [
        "'E exatamente isso que o conceito de [X] responde. Vamos construir o mecanismo do zero.'",
    ],
    "exemplo_desfecho_fraco": "Marina, 29 anos, faz hemograma de rotina. O resultado volta com numeros alterados. O medico diz que as hemácias estao maiores que o normal. Como um exame consegue revelar isso? [PROBLEMA: nada aconteceu com Marina. Nenhuma consequencia. O estudante nao tem nada para querer entender.]",
    "exemplo_desfecho_forte": "Marina, 29 anos, faz hemograma de rotina sem esperar nada. Três dias depois, o medico a chama de volta. Nao para dar o resultado por telefone — para conversar pessoalmente. Ela entra no consultorio achando que seria algo simples. O medico olha os exames e diz que as hemácias dela estao produzindo menos oxigenio do que deveriam, mas o corpo ainda nao deu sinal claro disso. 'Seu organismo esta compensando algo', ele diz. 'Ainda.' Marina sai sem entender exatamente o que isso significa. Como e possivel que o sangue de alguem esteja falhando em silencio — sem febre, sem dor, sem nenhum aviso — e um exame simples consiga ver isso antes do proprio corpo avisar? [CORRETO: algo aconteceu. Ha consequencia. Ha misterio real. O estudante quer saber.]",
    "sinal_que_funcionou": [
        "O estudante sente que tem uma pergunta real sem resposta.",
        "O estudante percebe por que o conceito existe antes de aprender o que ele e.",
    ],
    "transicao_proxima_etapa": """Apos apresentar a situacao e a pergunta geradora, sinalize: 'E exatamente isso que o conceito de [X] responde. Vamos construir o mecanismo do zero.' Nao resolva a pergunta ainda.""",
    "parada_obrigatoria": "NAO execute o proximo modulo. Aguarde confirmacao explicita do usuario antes de continuar.",
}
