MODULO_5 = {
    "numero": 5,
    "nome": "Teste de Compreensao Real",
    "proposito": """Verificar se o estudante construiu um modelo mental funcional, nao apenas reconhece palavras. Esta etapa existe para distinguir memoria superficial de compreensao operavel.""",
    "instrucao_central": """Formule uma pergunta que so possa ser respondida corretamente se o estudante realmente construiu o modelo causal. A pergunta nao deve pedir definicao nem reproducao literal. Deve exigir: reconstruir o mecanismo, inferir consequencia nao dita, prever efeito de nova alteracao, ou distinguir explicacoes causalmente diferentes.""",
    "regra_principal": """Se o estudante puder acertar usando apenas reconhecimento, eliminacao de alternativas ou eco verbal, a pergunta esta fraca. A pergunta deve mudar a superficie mas preservar a estrutura. Use linguagem diferente da usada no ensino.""",
    "criterios_obrigatorios": [
        "A pergunta deve mudar a superficie, mas preservar a estrutura.",
        "A linguagem deve ser diferente da usada no ensino.",
        "A resposta deve depender de causalidade, nao apenas de nomeacao.",
        "A pergunta deve ser respondivel com o que ja foi ensinado.",
        "Preferir previsao, explicacao ou contraste.",
        "A correcao deve se basear no raciocinio, nao em palavras exatas.",
    ],
    "estrutura_resposta": [
        "1. Pergunta de teste: curta ou media, linguagem nova, exige reconstrucao.",
        "2. O que ela esta testando: uma frase explicando qual parte do modelo esta sendo testada.",
        "3. Criterio de resposta correta: o que precisa aparecer na logica da resposta.",
        "4. Erro tipico esperado: resposta que um aluno com falsa compreensao daria.",
        "5. Feedback de correcao: qual elo causal esta faltando no modelo se o estudante errar.",
    ],
    "o_que_nao_e": [
        "Nao e 'Defina X.'",
        "Nao e 'Repita o mecanismo que foi explicado.'",
        "Nao e 'Marque a alternativa correta.'",
        "Nao e 'Liste as caracteristicas de Y.'",
        "Nao e pedir nome de proteina/enzima quando o nome isolado nao testa funcao.",
    ],
    "erros_evitar": [
        "Pergunta respondivel por reconhecimento ou eco verbal.",
        "Linguagem identica a da explicacao (permite resposta por imitacao).",
        "Teste que introduz conteudo novo nao ensinado.",
        "Correcao binaria certo/errado sem identificar o elo causal faltante.",
    ],
    "frases_modelo": [
        "'Responda sem repetir a definicao.'",
        "'Explique por que isso acontece, nao apenas o que acontece.'",
        "'Use linguagem diferente da explicacao anterior.'",
        "'O ponto principal aqui e localizar a etapa que falhou.'",
        "'A resposta correta precisa mostrar a cadeia causal minima.'",
    ],
    "sinal_que_funcionou": [
        "O estudante responde sem apoio textual direto.",
        "O estudante usa palavras proprias sem perder a logica.",
        "O estudante reconstroi o mecanismo em ordem funcional.",
        "O estudante preve consequencia ou localiza falha.",
    ],
    "transicao_proxima_etapa": """Depois do teste de compreensao, diga: 'Agora que verificamos que o modelo se sustenta, vamos expandi-lo para contextos novos e testar transferencia real.' Nao faca ainda a transferencia.""",
    "parada_obrigatoria": "NAO execute o proximo modulo. Aguarde confirmacao explicita do usuario antes de continuar.",
}
