MODULO_4 = {
    "numero": 4,
    "nome": "O Que Muda se Algo Falha, e Bloqueado ou se Altera",
    "proposito": """Converter o modelo em algo manipulavel. O estudante deve conseguir alterar mentalmente uma variavel do sistema e prever as consequencias locais e globais. Compreensao real inclui raciocinio causal e contrafactual.""",
    "instrucao_central": """Depois de explicar como o sistema funciona normalmente, mostre o que acontece quando uma etapa falha, e bloqueada, exagerada ou ocorre no lugar errado. A forma correta e: estado normal -> ponto de falha -> etapa imediatamente afetada -> efeito em cascata -> manifestacao observavel.""",
    "regra_principal": """A falha nunca deve ser apresentada como lista solta de 'se X ocorre Y'. Ela deve ser tratada como perturbacao em uma cadeia causal ja montada. Diferencie ausencia, excesso e desorganizacao.""",
    "criterios_obrigatorios": [
        "Escolha explicitamente o ponto de alteracao (ausencia, bloqueio, excesso, desorganizacao).",
        "Mostre a primeira consequencia direta antes de pular para o sintoma final.",
        "Siga a cascata ate o fenomeno observavel.",
        "Diferencie ausencia, excesso e ativacao fora de contexto.",
        "Use contraste com o funcionamento normal.",
        "Inclua valor diagnostico: como a falha aparece em sinais, sintomas, exames.",
    ],
    "estrutura_resposta": [
        "1. Funcionamento normal resumido (2-4 frases).",
        "2. Ponto de falha ou alteracao: o que foi retirado, bloqueado, exagerado ou desorganizado.",
        "3. Primeira consequencia local.",
        "4. Propagacao da alteracao pelas etapas seguintes.",
        "5. Manifestacao observavel (corpo, exame, caso clinico, laboratorio).",
        "6. Leitura diagnostica ou funcional: por que essa manifestacao faz sentido.",
        "7. Frase de fechamento: 'Se [X] falha, entao [Y] muda primeiro, o que leva a [Z], resultando em [W].'",
    ],
    "o_que_nao_e": [
        "Nao e lista de doencas associadas ao tema.",
        "Nao e enumeracao de sintomas sem mecanismo.",
        "Nao e patologia decorada separada da fisiologia.",
        "Nao e descricao de caso clinico sem localizar o ponto de falha.",
    ],
    "erros_evitar": [
        "Pular a primeira consequencia local (ir direto da alteracao molecular ao sintoma final).",
        "Tratar toda falha como ausencia (excesso e desorganizacao sao diferentes).",
        "Nao contrastar com o normal.",
        "Confundir marcador com mecanismo.",
        "Parar cedo demais antes do efeito observavel.",
    ],
    "frases_modelo": [
        "'Em condicoes normais, esta etapa faria...'",
        "'Se esse componente falha, a primeira coisa que muda e...'",
        "'Como essa etapa alimenta a seguinte, o efeito se propaga para...'",
        "'No nivel observavel, isso aparece como...'",
        "'Isso faz sentido porque o sistema dependia de...'",
    ],
    "sinal_que_funcionou": [
        "O estudante diz qual peca foi alterada.",
        "O estudante preve a primeira consequencia local.",
        "O estudante segue a cascata ate um efeito observavel.",
        "O estudante distingue falha por ausencia, bloqueio, excesso ou desorganizacao.",
    ],
    "transicao_proxima_etapa": """Depois de mostrar o que muda quando o sistema falha, diga: 'Agora que o mecanismo e suas falhas ficaram claros, vamos testar se o modelo realmente se sustenta com uma pergunta que nao pode ser resolvida por mera repeticao.' Nao faca ainda o teste.""",
    "parada_obrigatoria": "NAO execute o proximo modulo. Aguarde confirmacao explicita do usuario antes de continuar.",
}
