MODULO_2 = {
    "numero": 2,
    "nome": "Modelo Causal Explicito",
    "proposito": """Responder a pergunta gerada no Modulo 1 por meio de uma cadeia causal explicita. Transformar informacao solta em estrutura funcional. O estudante deve conseguir rodar o mecanismo na cabeca.""",
    "instrucao_central": """Explique o conceito como uma sequencia causal rastreavel, passo a passo, mostrando como um evento leva ao proximo. A estrutura padrao e: estado inicial -> gatilho -> mecanismo intermediario -> consequencia local -> consequencia sistemica -> efeito observavel.""",
    "regra_principal": """Nao pule elos causais. Cada etapa deve responder implicitamente 'por que?'. O estudante deve conseguir prever o proximo passo. Conecte mecanismo ao fenomeno observavel.""",
    "criterios_obrigatorios": [
        "Nao comece pela definicao formal. A definicao pode aparecer depois, mas so apos o mecanismo comecar.",
        "Nao pule elos causais. Nunca use 'isso leva a' como ponte vazia.",
        "Evite compressao excessiva. Se ha etapas intermediarias, elas devem aparecer.",
        "Cada etapa deve responder implicitamente a pergunta 'por que?'.",
        "O estudante deve conseguir prever o proximo passo.",
        "Sempre que possivel, conecte mecanismo e fenomeno observavel.",
    ],
    "estrutura_resposta": [
        "1. Estado inicial: como o sistema funciona normalmente antes do problema.",
        "2. Gatilho: o que inicia a mudanca.",
        "3. Cadeia causal: o que mudou primeiro, por que essa mudanca produz a proxima, o que cada etapa altera.",
        "4. Efeito final: resultado observavel (sintoma, sinal, resposta fisiologica, efeito terapeutico).",
        "5. Frase de fechamento: 'Em outras palavras: [X] acontece porque [Y], o que leva a [Z], resultando em [W].'",
    ],
    "o_que_nao_e": [
        "Nao e lista de caracteristicas.",
        "Nao e definicao de livro.",
        "Nao e resumo enciclopédico.",
        "Nao e nomeacao de componentes sem mostrar funcao.",
        "Nao e seta vazia entre termos tecnicos.",
    ],
    "erros_evitar": [
        "Salto causal: explicar inicio e fim sem o meio.",
        "Jargao como disfarce de compreensao.",
        "Explicacao circular.",
        "Associacao tratada como mecanismo.",
        "Macro sem micro: descrever efeito clinico sem mostrar o nivel funcional.",
    ],
    "frases_modelo": [
        "'Em condicoes normais, ...'",
        "'O processo comeca quando ...'",
        "'Isso altera ...'",
        "'Como consequencia, ...'",
        "'A etapa seguinte e ...'",
        "'No fim, isso se manifesta como ...'",
    ],
    "sinal_que_funcionou": [
        "O estudante recontar o mecanismo em ordem.",
        "O estudante dizer o que acontece se uma etapa falhar.",
        "O estudante prever um efeito observavel a partir do mecanismo.",
        "O estudante distinguir causa, etapa intermediaria e consequencia final.",
    ],
    "transicao_proxima_etapa": """Depois de explicar o mecanismo, diga: 'Agora que o mecanismo esta montado, vamos traduzir essa logica para um dominio que ja lhe e familiar, para consolidar o modelo.' Nao introduza ainda a analogia.""",
    "parada_obrigatoria": "NAO execute o proximo modulo. Aguarde confirmacao explicita do usuario antes de continuar.",
}
