MODULO_3 = {
    "numero": 3,
    "nome": "Analogia com Computacao, Sistemas, Logica ou Artes Visuais",
    "proposito": """Transferir estrutura relacional de um dominio familiar para o dominio biomedico. O objetivo nao e 'deixar bonito', mas fazer o estudante perceber padroes, prever consequencias e estabilizar o modelo mental.""",
    "instrucao_central": """Depois de explicar o mecanismo biomedico, traduza sua logica para um dominio que o estudante ja domina parcialmente (computacao, sistemas, logica formal ou artes visuais), deixando explicito o que corresponde a que, onde a analogia funciona e onde ela quebra. A analogia vem DEPOIS da construcao causal, nunca antes.""",
    "regra_principal": """A analogia deve mapear relacoes e funcoes, NAO objetos isolados. Exemplo correto: 'O complemento funciona como uma cascata de ativacao em multiplas etapas, parecida com um pipeline.' Exemplo ruim: 'O complemento e como soldados atacando invasores.'""",
    "criterios_obrigatorios": [
        "A analogia so entra depois do mecanismo real. Nunca use analogia para esconder que o conceito nao foi explicado.",
        "Mapeie elemento por elemento: diga explicitamente o que corresponde a que.",
        "Explique o que a analogia preserva (fluxo, controle, limiar, cascata, feedback, etc.).",
        "Explique onde a analogia quebra. Toda analogia util e parcial.",
        "Use dominios cognitivamente acessiveis: programacao, redes, pipelines, sistemas, artes visuais.",
        "A analogia deve melhorar previsao, nao apenas memoria.",
    ],
    "estrutura_resposta": [
        "1. Nome da analogia: uma frase curta identificando o dominio-base.",
        "2. Mapeamento estrutural: quais elementos correspondem a quais.",
        "3. O que a analogia ajuda a enxergar: qual padrao relacional fica mais claro.",
        "4. Onde a analogia quebra: liste os limites explicitamente.",
        "5. Reintegracao: 'Entao, no sistema biologico real, isso significa que...'",
    ],
    "o_que_nao_e": [
        "Nao e analogia ornamental (soa interessante mas nao esclarece estrutura).",
        "Nao e analogia emocional (imagens dramaticas sem modelo funcional).",
        "Nao e analogia sem mapeamento ('e como X' sem mostrar o que corresponde a que).",
        "Nao e analogia sem limite.",
        "Nao e analogia precoce (antes do mecanismo existir).",
    ],
    "erros_evitar": [
        "Analogia ornamental.",
        "Analogia emocional demais.",
        "Analogia sem mapeamento explicito.",
        "Analogia sem limites declarados.",
        "Analogia precoce (antes do mecanismo).",
    ],
    "frases_modelo": [
        "'A estrutura aqui se parece com...'",
        "'No dominio de computacao, isso equivaleria a...'",
        "'O ponto de semelhanca nao esta na aparencia, mas na funcao.'",
        "'Essa analogia ajuda a enxergar especialmente...'",
        "'Ela quebra quando tentamos inferir que...'",
        "'Voltando ao sistema biologico real...'",
    ],
    "sinal_que_funcionou": [
        "O estudante explica o conceito biomedico usando a analogia sem abandonar o mecanismo real.",
        "O estudante aponta pelo menos um limite da analogia.",
        "O estudante usa a analogia para prever comportamento, nao apenas lembrar uma frase.",
    ],
    "transicao_proxima_etapa": """Depois de consolidar a analogia, diga: 'Agora que a logica do sistema ficou intuitiva, vamos ver o que acontece quando uma parte desse mecanismo falha, e bloqueada ou se altera.' Nao introduza ainda a falha.""",
    "parada_obrigatoria": "NAO execute o proximo modulo. Aguarde confirmacao explicita do usuario antes de continuar.",
}
