MODULO_6 = {
    "numero": 6,
    "nome": "Transferencia para Novos Contextos",
    "proposito": """Transformar um modelo local em esquema mais geral e reutilizavel. Verificar se o estudante consegue reconhecer o mesmo principio organizador em outro contexto, com outra superficie, outro vocabulario, outra escala ou outro problema.""",
    "instrucao_central": """Depois que o estudante mostrou compreensao no contexto original, apresente um novo contexto e peca que identifique: o que permanece estruturalmente igual, o que muda na superficie e como o modelo deve ser adaptado.""",
    "regra_principal": """A Etapa 6 deve obrigar o estudante a responder: 1) O que neste novo caso e estruturalmente igual? 2) O que mudou apenas na superficie? 3) Que ajustes o modelo exige? Comece por near transfer antes de exigir far transfer.""",
    "criterios_obrigatorios": [
        "O novo contexto deve preservar a estrutura central do conceito.",
        "A atividade deve pedir comparacao explicita.",
        "O estudante deve identificar o principio geral.",
        "Inclua pelo menos uma diferenca relevante que exija adaptacao do modelo.",
        "Comece por near transfer antes de far transfer.",
        "A correcao deve valorizar mapeamento estrutural, nao palavras exatas.",
    ],
    "estrutura_resposta": [
        "1. Novo contexto: caso novo com linguagem ou cenario diferente.",
        "2. Pergunta de transferencia: o que permanece igual, o que mudou, como aplicar o modelo.",
        "3. O que esta sendo transferido: qual principio geral esta em jogo.",
        "4. Criterio de resposta correta: o que precisa aparecer para que a transferencia seja real.",
        "5. Erro tipico esperado: confusao de um estudante ainda preso a superficie.",
        "6. Feedback de correcao: como reconduzir ao principio estrutural.",
    ],
    "o_que_nao_e": [
        "Nao e repetir o mesmo caso com nomes trocados.",
        "Nao e introduzir assunto novo sem ponte estrutural.",
        "Nao e pedir criatividade livre sem criterio.",
        "Nao e premiar semelhanca superficial.",
    ],
    "erros_evitar": [
        "Pseudo-transferencia (caso novo mas resposta identica sem adaptacao).",
        "Transferencia impossivel (caso tao distante que exige conhecimento nao ensinado).",
        "Superficie enganosa sem apoio para comparar estrutura.",
        "Generalizacao indevida.",
        "Falta de explicitacao do principio a ser transferido.",
    ],
    "frases_modelo": [
        "'O que, neste novo caso, permanece estruturalmente igual?'",
        "'O que mudou apenas na superficie?'",
        "'Qual principio geral continua valido aqui?'",
        "'Que parte do modelo precisa ser ajustada?'",
        "'Nao compare os objetos; compare as relacoes.'",
    ],
    "sinal_que_funcionou": [
        "O estudante identifica o principio geral por tras de dois casos.",
        "O estudante separa estrutura de superficie.",
        "O estudante adapta o modelo sem descarta-lo.",
        "O estudante explica por que a transferencia e valida.",
    ],
    "transicao_proxima_etapa": """Depois da transferencia, encerre o ciclo com: 'Neste ponto, o conceito deixou de ser apenas uma explicacao local e passou a funcionar como um esquema reutilizavel.'""",
    "parada_obrigatoria": "NAO execute o proximo modulo. Aguarde confirmacao explicita do usuario antes de continuar.",
}
